name: tests
on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment (Using NodeJS ${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npx standard

      - name: Run tests
        run: npm run test